### ISSUE TITLE
Choc spaced version

### ISSUE THREAD

**Issue by yohcop** [Bastardkb/Dilemma#18]
Hi!

This is awesome!
Since it's meant to be a portable keyboard with input device, i was wondering if a choc-spaced version could be considered.

I realize with the case and all, it's not as trivial as just changing the spacing of the matrix :)

Best,

**Comment by bstiq** [comment]
Hello,

I have no plans for a choc version at the moment.
It should be pretty easy to do though, just change the positioning of the switches and re-wire the matrix.
You will also have to change the edge cuts though, and the case will not be compatible anymore.

Regards,
