### ISSUE TITLE
Dilemma DIY - on off button not wired properly

### ISSUE THREAD

**Issue by bstiq** [Bastardkb/Dilemma#7]
As mentioned by charly and freznel
When battery is conected, Vcc and Gnd are connected

Fix: on/off button should be wired like on the adapter v2

**Comment by bstiq** [comment]
Tag DIY0.1c should fix it.

@freznel10 could you maybe take a look at the schematic and wiring when you have time to confirm? Then I will order new DIY ones with the next PCB order.

**Comment by 0xcharly** [comment]
I'm no expert, but from a cursory look, this fix LGTM.  I'll order a small batch to test.

**Comment by bstiq** [comment]
@0xcharly Can you confirm everything works ?

**Comment by 0xcharly** [comment]
I can confirm that it works with `DIY0.1c`. I have been using this version for a few days now, and the on/off feature works as expected.
